Repository codehaus-plexus/plexus-compiler, pull requests merged in 2022-03, with the labels that each got.

#189 no deploy its pom
  plexus-compiler-its/pom.xml
Labels: removed

#198 minor cleanup
  plexus-compiler-api/src/main/java/org/codehaus/plexus/compiler/AbstractCompiler.java
  plexus-compiler-api/src/main/java/org/codehaus/plexus/compiler/CompilerMessage.java
  plexus-compiler-api/src/main/java/org/codehaus/plexus/compiler/CompilerOutputStyle.java
  plexus-compiler-api/src/main/java/org/codehaus/plexus/compiler/util/StreamPumper.java
  plexus-compiler-api/src/main/java/org/codehaus/plexus/compiler/util/scan/AbstractSourceInclusionScanner.java
  plexus-compiler-api/src/main/java/org/codehaus/plexus/compiler/util/scan/SimpleSourceInclusionScanner.java
  plexus-compiler-api/src/main/java/org/codehaus/plexus/compiler/util/scan/StaleSourceScanner.java
  plexus-compiler-api/src/main/java/org/codehaus/plexus/compiler/util/scan/mapping/SingleTargetSourceMapping.java
  plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavacCompiler.java
Labels: maintenance

#199 add paremeter to configure javac feature --enable-preview
  plexus-compiler-api/src/main/java/org/codehaus/plexus/compiler/CompilerConfiguration.java
  plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavacCompiler.java
Labels: enhancement

#202 [MCOMPILER-402] Add implicitOption to CompilerConfiguration
  plexus-compiler-api/src/main/java/org/codehaus/plexus/compiler/CompilerConfiguration.java
  plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavacCompiler.java
Labels: enhancement

#204 fully ignore any possible jdk bug
  plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavaxToolsCompiler.java
Labels: enhancement
