Repository codehaus-plexus/plexus-compiler, pull requests merged in 2022-02, with the labels that each got.

#184 javac dump debug file should not be written in classes directory as it will be included in jar. change directory and make name configurable
  plexus-compiler-api/src/main/java/org/codehaus/plexus/compiler/CompilerConfiguration.java
  plexus-compilers/plexus-compiler-j2objc/README.md
  plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavacCompiler.java
Labels: enhancement

#186 make java 11 as project base but keep javac release 8, we will be able to upgrade ecj and errorprone
  .github/workflows/maven.yml
  pom.xml
Labels: enhancement

#170 Issue #106: Retain error messages from annotation processors
  plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavacCompiler.java
  plexus-compilers/plexus-compiler-javac/src/test/java/org/codehaus/plexus/compiler/javac/JavacCompilerTest.java
Labels: bug

#188 remove jikes compiler
  plexus-compilers/plexus-compiler-jikes/pom.xml
  plexus-compilers/plexus-compiler-jikes/src/main/java/org/codehaus/plexus/compiler/jikes/JikesCompiler.java
  plexus-compilers/plexus-compiler-jikes/src/site/site.xml
  plexus-compilers/plexus-compiler-jikes/src/test-input/src/main/org/codehaus/foo/Bad.java
  plexus-compilers/plexus-compiler-jikes/src/test-input/src/main/org/codehaus/foo/Deprecation.java
  plexus-compilers/plexus-compiler-jikes/src/test-input/src/main/org/codehaus/foo/ExternalDeps.java
  plexus-compilers/plexus-compiler-jikes/src/test-input/src/main/org/codehaus/foo/Person.java
  plexus-compilers/plexus-compiler-jikes/src/test-input/src/main/org/codehaus/foo/ReservedWord.java
  plexus-compilers/plexus-compiler-jikes/src/test-input/src/main/org/codehaus/foo/UnknownSymbol.java
  plexus-compilers/plexus-compiler-jikes/src/test-input/src/main/org/codehaus/foo/WrongClassname.java
  plexus-compilers/plexus-compiler-jikes/src/test/java/org/codehaus/plexus/compiler/jikes/JikesCompilerTest.java
  plexus-compilers/pom.xml
  src/site/apt/index.apt
Labels: chore

#194 Import BOM of JUnit to manage all its dependencies
  plexus-compilers/pom.xml
  pom.xml
Labels: build

#193 [eclipse-compiler] Resort sources to have module-info.java first
  plexus-compilers/plexus-compiler-eclipse/pom.xml
  plexus-compilers/plexus-compiler-eclipse/src/main/java/org/codehaus/plexus/compiler/eclipse/EclipseJavaCompiler.java
  plexus-compilers/plexus-compiler-eclipse/src/test/java/org/codehaus/plexus/compiler/eclipse/EclipseJavaCompilerTest.java
Labels: bug
