Repository codehaus-plexus/plexus-compiler, pull requests merged in 2024-02, with the labels that each got.

#362 Only use "-release" parameter with javac 9+
  plexus-compilers/plexus-compiler-javac/src/main/java/org/codehaus/plexus/compiler/javac/JavacCompiler.java
Labels: enhancement

#361 Lazy providers and better error reporting
  plexus-compiler-its/src/main/it/MCOMPILER-346-mre/pom.xml
  plexus-compiler-its/src/main/it/aspectj-compiler/pom.xml
  plexus-compiler-its/src/main/it/eclipse-compiler-mapstruct/pom.xml
  plexus-compiler-its/src/main/it/eclipse-compiler-procpath/pom.xml
  plexus-compiler-its/src/main/it/error-prone-compiler/pom.xml
  plexus-compiler-its/src/main/it/missing-warnings/pom.xml
  plexus-compiler-its/src/main/it/simple-eclipse-compiler-fail/pom.xml
  plexus-compiler-its/src/main/it/simple-eclipse-compiler/pom.xml
  plexus-compiler-its/src/main/it/simple-javac-fork/pom.xml
  plexus-compiler-its/src/main/it/simple-javac/pom.xml
  plexus-compiler-manager/src/main/java/org/codehaus/plexus/compiler/manager/DefaultCompilerManager.java
  plexus-compiler-manager/src/main/java/org/codehaus/plexus/compiler/manager/NoSuchCompilerException.java
Labels: enhancement

#368 Path.relativize() may throw exception if source and build directories are on different Windows drives
  plexus-compiler-api/src/main/java/org/codehaus/plexus/compiler/AbstractCompiler.java
Labels: bug

#370 Bump project version to 2.15.0-SNAPSHOT
  plexus-compiler-api/pom.xml
  plexus-compiler-its/pom.xml
  plexus-compiler-manager/pom.xml
  plexus-compiler-test/pom.xml
  plexus-compilers/plexus-compiler-aspectj/pom.xml
  plexus-compilers/plexus-compiler-csharp/pom.xml
  plexus-compilers/plexus-compiler-eclipse/pom.xml
  plexus-compilers/plexus-compiler-javac-errorprone/pom.xml
  plexus-compilers/plexus-compiler-javac/pom.xml
  plexus-compilers/pom.xml
  pom.xml
Labels: maintenance
